import "@uploadthing/react/styles.css";
import "~/styles/globals.css";

import { Toaster } from "~/components/ui/sonner";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "T3 Gallery",
  description: "Generated by Ahmed Senousy",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} dark`}>
        {children}
        {modal}
        
        <div id="modal-root" />
        <Toaster />
      </body>
    </html>
  );
}
